import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { ComplaintDetail } from '../../components/complaints/ComplaintDetail'
import { ErrorMessage, LoadingSpinner } from '../../components/common/Feedback'
import { PageHeader } from '../../components/common/PageTools'
import { getComplaint, updateComplaintPriority, updateComplaintStatus } from '../../services/complaintService'

const nextStatuses = { OPEN: ['IN_PROGRESS', 'RESOLVED'], IN_PROGRESS: ['RESOLVED'], RESOLVED: [] }
export function AdminComplaintDetailsPage() { const { id } = useParams(); const [complaint, setComplaint] = useState(null), [error, setError] = useState(''), [saving, setSaving] = useState(false), [status, setStatus] = useState(''), [note, setNote] = useState(''); const load = () => { setError(''); getComplaint(id).then((data) => { setComplaint(data); setStatus(nextStatuses[data.status][0] || '') }).catch((err) => setError(err.message)) }; useEffect(load, [id]); const changeStatus = async (event) => { event.preventDefault(); setSaving(true); try { await updateComplaintStatus(id, { status, note: note || null }); setNote(''); load() } catch (err) { setError(err.message) } finally { setSaving(false) } }; const changePriority = async (event) => { const priority = event.target.value; setSaving(true); try { await updateComplaintPriority(id, { priority }); load() } catch (err) { setError(err.message) } finally { setSaving(false) } }; if (error && !complaint) return <ErrorMessage message={error} onRetry={load} />; if (!complaint) return <LoadingSpinner />; const canUpdate = nextStatuses[complaint.status].length > 0; return <><PageHeader title={`Complaint #${complaint.id}`} description={`Reported by ${complaint.resident_name}.`} />{error && <ErrorMessage message={error} />}<div className="admin-actions">{canUpdate ? <form onSubmit={changeStatus}><label>Update status<select value={status} onChange={(event) => setStatus(event.target.value)}>{nextStatuses[complaint.status].map((item) => <option key={item}>{item}</option>)}</select></label><label>Note<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength="500" /></label><button className="primary-button compact" disabled={saving}>Save status</button></form> : <p className="closed-message">This complaint is resolved and cannot be modified.</p>}<label>Priority<select value={complaint.priority} disabled={!canUpdate || saving} onChange={changePriority}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label></div><ComplaintDetail complaint={complaint} /></> }
